package model

const (
	USER_ROLE        = 1
	DEALER_ROLE      = 2
	LOGIST_ROLE      = 3
	BROKER_ROLE      = 4
	CAR_SERVICE_ROLE = 5
	ROLE_COUNT       = 5

	APPLICATION_STATUS_PENDING  = 1
	APPLICATION_STATUS_APPROVED = 2
	APPLICATION_STATUS_REJECTED = 3
	APPLICATION_STATUS_COUNT    = 3
)
